# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kmeans.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ckmeans.proto\"\"\n\ncoordinate\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"/\n\x05\x63hunk\x12\x13\n\x0bstart_index\x18\x01 \x01(\x05\x12\x11\n\tend_index\x18\x02 \x01(\x05\"B\n\x07mapInfo\x12\x17\n\x07indices\x18\x01 \x01(\x0b\x32\x06.chunk\x12\x1e\n\tcentroids\x18\x02 \x03(\x0b\x32\x0b.coordinate\"1\n\x06keyVal\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x1a\n\x05value\x18\x02 \x01(\x0b\x32\x0b.coordinate\"\"\n\treturnMap\x12\x15\n\x04\x64ict\x18\x01 \x03(\x0b\x32\x07.keyVal\"\x18\n\x05reply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32J\n\x06KMeans\x12\x1d\n\x03Map\x12\x08.mapInfo\x1a\n.returnMap\"\x00\x12!\n\tPartition\x12\n.returnMap\x1a\x06.reply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kmeans_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_COORDINATE']._serialized_start=16
  _globals['_COORDINATE']._serialized_end=50
  _globals['_CHUNK']._serialized_start=52
  _globals['_CHUNK']._serialized_end=99
  _globals['_MAPINFO']._serialized_start=101
  _globals['_MAPINFO']._serialized_end=167
  _globals['_KEYVAL']._serialized_start=169
  _globals['_KEYVAL']._serialized_end=218
  _globals['_RETURNMAP']._serialized_start=220
  _globals['_RETURNMAP']._serialized_end=254
  _globals['_REPLY']._serialized_start=256
  _globals['_REPLY']._serialized_end=280
  _globals['_KMEANS']._serialized_start=282
  _globals['_KMEANS']._serialized_end=356
# @@protoc_insertion_point(module_scope)
