# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shopping.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eshopping.proto\"\x1c\n\x0bstringReply\x12\r\n\x05reply\x18\x01 \x01(\t\"9\n\nSellerInfo\x12\x16\n\x0eseller_address\x18\x01 \x01(\t\x12\x13\n\x0bseller_uuid\x18\x02 \x01(\t\"\xdb\x01\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12 \n\x08\x63\x61tegory\x18\x03 \x01(\x0e\x32\x0e.Item.Category\x12\x10\n\x08quantity\x18\x04 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x13\n\x0bseller_uuid\x18\x06 \x01(\t\x12\x16\n\x0eseller_address\x18\x07 \x01(\t\x12\r\n\x05price\x18\x08 \x01(\x02\"4\n\x08\x43\x61tegory\x12\x0f\n\x0b\x45LECTRONICS\x10\x00\x12\x0b\n\x07\x46\x41SHION\x10\x01\x12\n\n\x06OTHERS\x10\x02\"f\n\nItemUpdate\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05price\x18\x02 \x01(\x02\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12\x13\n\x0bseller_uuid\x18\x04 \x01(\t\x12\x16\n\x0eseller_address\x18\x05 \x01(\t\"A\n\nBuyRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\x15\n\rbuyer_address\x18\x03 \x01(\t\"4\n\x0fWishListRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x15\n\rbuyer_address\x18\x02 \x01(\t\"@\n\x0bRateRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x15\n\rbuyer_address\x18\x02 \x01(\t\x12\x0e\n\x06rating\x18\x03 \x01(\x05\x32\x82\x03\n\x0bMarketPlace\x12-\n\x0eRegisterSeller\x12\x0b.SellerInfo\x1a\x0c.stringReply\"\x00\x12!\n\x08SellItem\x12\x05.Item\x1a\x0c.stringReply\"\x00\x12)\n\nUpdateItem\x12\x0b.ItemUpdate\x1a\x0c.stringReply\"\x00\x12#\n\nDeleteItem\x12\x05.Item\x1a\x0c.stringReply\"\x00\x12,\n\x12\x44isplaySellerItems\x12\x0b.SellerInfo\x1a\x05.Item\"\x00\x30\x01\x12\x1e\n\nSearchItem\x12\x05.Item\x1a\x05.Item\"\x00\x30\x01\x12&\n\x07\x42uyItem\x12\x0b.BuyRequest\x1a\x0c.stringReply\"\x00\x12\x31\n\rAddToWishList\x12\x10.WishListRequest\x1a\x0c.stringReply\"\x00\x12(\n\x08RateItem\x12\x0c.RateRequest\x1a\x0c.stringReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shopping_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STRINGREPLY']._serialized_start=18
  _globals['_STRINGREPLY']._serialized_end=46
  _globals['_SELLERINFO']._serialized_start=48
  _globals['_SELLERINFO']._serialized_end=105
  _globals['_ITEM']._serialized_start=108
  _globals['_ITEM']._serialized_end=327
  _globals['_ITEM_CATEGORY']._serialized_start=275
  _globals['_ITEM_CATEGORY']._serialized_end=327
  _globals['_ITEMUPDATE']._serialized_start=329
  _globals['_ITEMUPDATE']._serialized_end=431
  _globals['_BUYREQUEST']._serialized_start=433
  _globals['_BUYREQUEST']._serialized_end=498
  _globals['_WISHLISTREQUEST']._serialized_start=500
  _globals['_WISHLISTREQUEST']._serialized_end=552
  _globals['_RATEREQUEST']._serialized_start=554
  _globals['_RATEREQUEST']._serialized_end=618
  _globals['_MARKETPLACE']._serialized_start=621
  _globals['_MARKETPLACE']._serialized_end=1007
# @@protoc_insertion_point(module_scope)
